### ISSUE TITLE
database file for 'clang32' does not exist

### ISSUE THREAD

**Issue by eko5624** [msys2/setup-msys2#216] opened 2022-05-01 00:41 UTC
```
warning: database file for 'clang32' does not exist (use '-Sy' to download)
  error: failed to prepare transaction (could not find database)
  Error: The process 'C:\Windows\system32\cmd.exe' failed with exit code 1
```

**Comment by Biswa96** [comment] 2022-05-01 01:53
Duplicate of https://github.com/msys2/setup-msys2/issues/215 which have been fixed recently.

**Comment by eko5624** [comment] 2022-05-01 02:35
Haven't fixed yet. 
https://github.com/eko5624/mpv-win64/runs/6243856398?check_suite_focus=true

**Comment by Biswa96** [comment] 2022-05-01 02:46
The changelog says "Enable CLANG32 when release is true". Not sure where to add that.

**Comment by jeremyd2019** [comment] 2022-05-01 02:54
Apparently a sync (`pacman -Sy`) needs to be done *after* adding clang32 to pacman.conf

**Comment by eko5624** [comment] 2022-05-01 02:55
so what I should do to fix this?

**Comment by Biswa96** [comment] 2022-05-01 02:58
Wondering why clang32 and clangarm64 were not added in pacman.conf yet. Then these type of workarounds would not require.

**Comment by eko5624** [comment] 2022-05-01 09:45
workarounds: don't use this:
```
      install: >-
        git
        base-devel
```

use this:
```
    - name: Install additional packages     
      shell: msys2 {0} 
      run: |
        pacman -Sy base-devel git --noconfirm
```

**Comment by Kha** [comment] 2022-05-01 09:59
Pinning the action to `v2.10.0` as in the commit above also works

**Comment by eine** [comment] 2022-05-01 11:06
@eko5624 @Kha are you using `update: false`?

**Comment by eko5624** [comment] 2022-05-01 13:19
@eine  Yes, I use default. By default, the installation is not updated.

**Comment by eine** [comment] 2022-05-01 14:52
This should be fixed now. In order to install packages on CLANG32, `release: true` (default) and `update: true` are required (see https://github.com/msys2/setup-msys2/commit/5bb19b04198a16a0282d7abcc1fdb877a1514790). Other use cases should not be affected.

**Closed by eine** 2022-05-01 14:52 UTC
